[package]
name = "phantom-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_superuser = "1.0.1"
regex = "1.7.1"
